export const categories = ['Game', 'Movie', 'Series', 'Anime', 'Book', 'Course', 'Application', 'Project', 'Link', 'Wishlist', 'Other'];
export const routeByCategory = { Game: 'games', Movie: 'media', Series: 'media', Anime: 'media', Book: 'learning', Course: 'learning', Application: 'applications', Project: 'projects', Link: 'links', Wishlist: 'wishlist', Other: 'inbox' };
export const statuses = ['Inbox', 'Planned', 'In Progress', 'Paused', 'Completed', 'Dropped', 'Archived'];
export const categoryStatuses = { Game: ['Backlog', 'Playing', 'Paused', 'Completed', 'Dropped', 'Replay'], Media: ['Watchlist', 'Watching', 'Paused', 'Completed', 'Dropped', 'Rewatch'], Learning: ['Planned', 'Learning', 'Paused', 'Completed', 'Dropped'], Application: ['Researching', 'Preparing', 'Ready to Apply', 'Applied', 'Interview', 'Accepted', 'Rejected', 'Deadline Passed'], Project: ['Idea', 'Planning', 'Building', 'Paused', 'Completed', 'Abandoned'] };
export const metadataDefaults = { Game: { platform: '', genre: '', completionType: '' }, Movie: { mediaType: 'Movie', season: '', currentEpisode: '', totalEpisodes: '' }, Series: { mediaType: 'Series', season: '', currentEpisode: '', totalEpisodes: '' }, Anime: { mediaType: 'Anime', season: '', currentEpisode: '', totalEpisodes: '' }, Book: { source: '', certification: '', certificateUrl: '' }, Course: { source: '', certification: '', certificateUrl: '' }, Application: { organization: '', deadline: '', requirements: [] }, Project: { description: '', technologies: '', githubUrl: '', demoUrl: '', deadline: '' }, Link: { linkCategory: 'Other', description: '', whySaved: '' }, Wishlist: { price: '', priority: 'Medium', purchaseStatus: 'Want' }, Other: {} };

export function uid() { return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
export function parseTags(value) { return String(value || '').split(',').map((tag) => tag.trim().replace(/^#/, '')).filter(Boolean).slice(0, 12); }
export function safeUrl(value) { try { const url = String(value || '').trim(); if (!url) return ''; const parsed = new URL(url); return ['http:', 'https:'].includes(parsed.protocol) ? parsed.href : ''; } catch { return ''; } }
export function normalizeItem(item) { const category = categories.includes(item?.category) ? item.category : 'Other'; const metadata = { ...metadataDefaults[category], ...(item?.metadata || {}) }; if (typeof metadata.requirements === 'string') { try { metadata.requirements = JSON.parse(metadata.requirements); } catch { metadata.requirements = []; } } if (Array.isArray(metadata.requirements) && metadata.requirements.length === 1 && String(metadata.requirements[0]?.text || '').trim().startsWith('[')) { try { metadata.requirements = JSON.parse(metadata.requirements[0].text); } catch { metadata.requirements = []; } } if (!Array.isArray(metadata.requirements) && category === 'Application') metadata.requirements = []; if (Array.isArray(metadata.requirements)) metadata.requirements = metadata.requirements.filter((requirement) => requirement && String(requirement.text || '').trim()).map((requirement) => ({ id: String(requirement.id || uid()), text: String(requirement.text).trim(), completed: Boolean(requirement.completed) })); return { id: String(item?.id || uid()), title: String(item?.title || '').trim(), type: String(item?.type || category), category, status: String(item?.status || 'Inbox'), progress: Math.max(0, Math.min(100, Number(item?.progress) || 0)), tags: Array.isArray(item?.tags) ? item.tags.map(String).slice(0, 30) : [], notes: String(item?.notes || ''), url: safeUrl(item?.url), createdAt: validDate(item?.createdAt) || Date.now(), updatedAt: validDate(item?.updatedAt) || Date.now(), startedAt: validDate(item?.startedAt), completedAt: validDate(item?.completedAt), metadata }; }
export function validDate(value) { const date = value ? new Date(value).getTime() : 0; return Number.isFinite(date) && date > 0 ? date : null; }
export function deadlineInfo(value) { const deadline = validDate(value); if (!deadline) return { label: 'No deadline', tone: 'none', days: null }; const days = Math.ceil((new Date(new Date(deadline).toDateString()).getTime() - new Date(new Date().toDateString()).getTime()) / 86400000); if (days < 0) return { label: 'Overdue', tone: 'overdue', days }; if (days === 0) return { label: 'Due today', tone: 'urgent', days }; if (days <= 3) return { label: `${days} day${days === 1 ? '' : 's'} left`, tone: 'urgent', days }; if (days <= 14) return { label: `${days} days left`, tone: 'soon', days }; return { label: `${days} days left`, tone: 'upcoming', days }; }
export function formatDate(value) { return value ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) : 'No date'; }
export function formatRelative(value) { if (!value) return ''; const days = Math.floor((Date.now() - value) / 86400000); return days <= 0 ? 'Today' : days === 1 ? 'Yesterday' : `${days}d ago`; }
export function getGreeting(hour = new Date().getHours()) { return hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'; }
export function applyTheme(theme) { document.documentElement.dataset.theme = theme; }
export function monthStart() { const date = new Date(); return new Date(date.getFullYear(), date.getMonth(), 1).getTime(); }
